import { GoogleGenAI, Type } from "@google/genai";
import { Track } from "../constants";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export interface TrackAnalysis {
  bpm: number;
  key: string;
  mood: string;
  energy: number;
  genre: string;
  transitionAdvice: string;
}

export const analyzeTrack = async (trackName: string, artist: string): Promise<TrackAnalysis> => {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Analyze this track for a DJ mix: "${trackName}" by ${artist}. Provide BPM, musical key, mood, energy level (1-10), genre, and a brief tip for transitioning into or out of it.`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            bpm: { type: Type.NUMBER },
            key: { type: Type.STRING },
            mood: { type: Type.STRING },
            energy: { type: Type.NUMBER },
            genre: { type: Type.STRING },
            transitionAdvice: { type: Type.STRING },
          },
          required: ["bpm", "key", "mood", "energy", "genre", "transitionAdvice"],
        },
      },
    });

    return JSON.parse(response.text || "{}");
  } catch (error) {
    console.error("AI Analysis failed:", error);
    return {
      bpm: 124,
      key: "Am",
      mood: "Energetic",
      energy: 8,
      genre: "Electronic",
      transitionAdvice: "Try a long crossfade on the breakdown.",
    };
  }
};

export const getTransitionAdvice = async (trackA: string, trackB: string): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `I am a DJ mixing from "${trackA}" into "${trackB}". Give me a creative and technical transition tip in 2 sentences.`,
    });
    return response.text || "Smoothly crossfade during the outro.";
  } catch (error) {
    return "Match the BPMs and swap the basslines during the drop.";
  }
};

export const getLyrics = async (trackName: string, artist: string): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Generate a short snippet of lyrics (4-6 lines) for a song titled "${trackName}" by ${artist} in the style of its genre.`,
    });
    return response.text || "Lyrics unavailable for this track.";
  } catch (error) {
    return "Unable to load lyrics.";
  }
};

export const getStemAdvice = async (trackName: string, stemType: string): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `I am isolating the ${stemType} of "${trackName}". Give me a 1-sentence tip on how to use this isolated stem in a live DJ mix.`,
    });
    return response.text || `Use the ${stemType} to build tension.`;
  } catch (error) {
    return `Great for layering over the next track's intro.`;
  }
};

export interface GeneratedTrack {
  title: string;
  artist: string;
  genre: string;
  bpm: number;
  mood: string;
  description: string;
}

export const generateMusicMetadata = async (prompt: string): Promise<GeneratedTrack> => {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Generate metadata for a new song based on this description: "${prompt}". Provide a title, artist name, genre, BPM, mood, and a short description.`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            title: { type: Type.STRING },
            artist: { type: Type.STRING },
            genre: { type: Type.STRING },
            bpm: { type: Type.NUMBER },
            mood: { type: Type.STRING },
            description: { type: Type.STRING },
          },
          required: ["title", "artist", "genre", "bpm", "mood", "description"],
        },
      },
    });

    return JSON.parse(response.text || "{}");
  } catch (error) {
    console.error("Music generation failed:", error);
    return {
      title: "AI Generated Anthem",
      artist: "Go DJ AI",
      genre: "Electronic",
      bpm: 128,
      mood: "Epic",
      description: "A high-energy track generated by Go DJ AI.",
    };
  }
};

export const getAutoDjSuggestion = async (
  currentTrack: Track,
  library: Track[],
  mood: string = 'energetic'
): Promise<{ trackId: string; reason: string }> => {
  try {
    const libraryInfo = library.map(t => ({ id: t.id, title: t.title, artist: t.artist }));
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Current track: "${currentTrack.title}" by ${currentTrack.artist}. 
      Library: ${JSON.stringify(libraryInfo)}.
      Target mood: ${mood}.
      Pick the best next track from the library to maintain the flow. Return the track ID and a 1-sentence reason.`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            trackId: { type: Type.STRING },
            reason: { type: Type.STRING },
          },
          required: ["trackId", "reason"],
        },
      },
    });

    return JSON.parse(response.text || "{}");
  } catch (error) {
    console.error("Auto-DJ suggestion failed:", error);
    // Fallback to a random track from library that isn't the current one
    const otherTracks = library.filter(t => t.id !== currentTrack.id);
    const randomTrack = otherTracks[Math.floor(Math.random() * otherTracks.length)] || library[0];
    return {
      trackId: randomTrack.id,
      reason: "Maintaining the energy with a library classic."
    };
  }
};
